In [10]:
import numpy as np
from tic_env import TictactoeEnv, OptimalPlayer

In [11]:
env = TictactoeEnv()

In [12]:
import random

In [29]:
# helper functions

#check if the game is over
def checkEnd(grid):
    # check rows and cols
    if np.any(np.sum(grid, axis=0) == 3) or np.any(np.sum(grid, axis=1) == 3):
        end = True
        winner = 'X'
    elif np.any(np.sum(grid, axis=0) == -3) or np.any(np.sum(grid, axis=1) == -3):
        end = True
        winner = 'O'
    # check diagnols
    elif grid[[0,1,2],[0,1,2]].sum() == 3 or grid[[0,1,2],[2,1,0]].sum() == 3:
        end = True
        winner = 'X'
    elif grid[[0,1,2],[0,1,2]].sum() == -3 or grid[[0,1,2],[2,1,0]].sum() == -3:
        end = True
        winner = 'O'
    # check if all the positions are filled
    elif (grid == 0).sum() == 0:
        end = True
        winner = None # no one wins
    else:
        end = False
        winner = None

    return end, winner


In [34]:
class QLearningAgent:
    def __init__(self, epsilon=0.2, alpha=0.1, gamma=0.9, player='X', env=None):
        self.epsilon = epsilon
        self.alpha = alpha
        self.gamma = gamma
        self.player = player
        if player == 'X':
            self.player_number = 1
        else: 
            self.player_number = -1
        self.env = env
        self.last_SA = None
        self.Q_table = {}

    def empty(self, grid):
        '''return all empty positions'''
        avail = []
        for i in range(9):
            pos = (int(i/3), i % 3)
            if grid[pos] == 0:
                avail.append(pos)
        return avail



    def check_q_table_and_update(self, grid):
        state = tuple(grid.flatten())
        if state not in self.Q_table:
            avail = self.empty(grid)
            self.Q_table[state] = {}
            for pos in avail:
                self.Q_table[state][pos] = 0

        if self.last_SA is not None:
            #check if all q values are zero
            all_zero = True
            for pos in self.Q_table[state]:
                if self.Q_table[state][pos] != 0:
                    all_zero = False
            if all_zero:
                #get random action
                supposed_action = random.choice(list(self.Q_table[state]))
            else:
                supposed_action = max(self.Q_table[state], key=self.Q_table[state].get)
            possible_grid = grid.copy()
            possible_grid[supposed_action] = self.player_number
            # check if the game is over
            reward = 0
            end, winner = checkEnd(possible_grid)
            if end:
                if winner:
                    if winner == self.player:
                        reward = 1
                    else:
                        reward = -1

            temporal_difference = reward + self.gamma * self.Q_table[state][supposed_action] - self.Q_table[self.last_SA[0]][self.last_SA[1]]
            self.Q_table[self.last_SA[0]][self.last_SA[1]] += self.alpha * temporal_difference

                


    def act(self, grid):
        if np.random.random() < self.epsilon:
            avail = self.empty(grid)
            return avail[random.randint(0, len(avail)-1)]

        else:
            state = tuple(grid.flatten())
            all_zero = True
            for pos in self.Q_table[state]:
                if self.Q_table[state][pos] != 0:
                    all_zero = False
            if all_zero:
                #get random action
                action = random.choice(list(self.Q_table[state]))
            else:
            # if not, go greedy
                action = max(self.Q_table[state], key=self.Q_table[state].get)
                
            return action





q_player = QLearningAgent(player='X', epsilon=0.2)
r_player = OptimalPlayer(epsilon=1, player='O')
grid, _, __ = env.observe()

#convert grid to tuple

print(q_player.Q_table)
print(grid)
q_player.check_q_table_and_update(grid)
# q_player.act(grid)
# print(q_player.act(grid))
print(q_player.Q_table)



{}
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
{(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0): {(0, 0): 0, (0, 1): 0, (0, 2): 0, (1, 0): 0, (1, 1): 0, (1, 2): 0, (2, 0): 0, (2, 1): 0, (2, 2): 0}}


In [14]:
env.reset()
grid, _, __ = env.observe()
player_opt = OptimalPlayer(epsilon=0., player='X')
player_q = QLearningAgent(epsilon=0.2, player='O')
for j in range(9):
    if env.current_player == player_opt.player:
        move = player_opt.act(grid)
    else:
        move = player_q.act(grid)

    grid, end, winner = env.step(move, print_grid=False)

    if end:
        print('-------------------------------------------')
        print('Game end, winner is player ' + str(winner))
        print('Optimal player = ' +  Turns[0])
        print('Random player = ' +  Turns[1])
        print(env.reward(winner))
        env.render()
        env.reset()
        break
    else:
        if env.current_player != player_q.player:
            last_q_value = q_player.Q[q_player.last_pos]
            delta_q = q_player.gamma * 


SyntaxError: invalid syntax (2273742928.py, line 25)

In [15]:
env.reset()
env.__dict__

{'grid': array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 'end': False,
 'winner': None,
 'player2value': {'X': 1, 'O': -1},
 'num_step': 0,
 'current_player': 'X'}

In [16]:
a = np.zeros((2,4))

print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
